# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'myapp.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QComboBox, QFormLayout,
    QFrame, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QTabWidget, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1000, 600))
        MainWindow.setMaximumSize(QSize(1000, 600))
        font = QFont()
        font.setFamilies([u"Trebuchet MS"])
        font.setPointSize(13)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.formLayout = QFormLayout(self.centralwidget)
        self.formLayout.setObjectName(u"formLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setFont(font)
        self.issuetab = QWidget()
        self.issuetab.setObjectName(u"issuetab")
        self.line = QFrame(self.issuetab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(650, -40, 20, 591))
        self.line.setFont(font)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.genrebox = QComboBox(self.issuetab)
        self.genrebox.setObjectName(u"genrebox")
        self.genrebox.setGeometry(QRect(680, 290, 291, 41))
        self.genrebox.setFont(font)
        self.genrelabel = QLabel(self.issuetab)
        self.genrelabel.setObjectName(u"genrelabel")
        self.genrelabel.setGeometry(QRect(680, 250, 261, 31))
        self.genrelabel.setFont(font)
        self.viewmode = QGroupBox(self.issuetab)
        self.viewmode.setObjectName(u"viewmode")
        self.viewmode.setGeometry(QRect(670, 10, 271, 101))
        self.viewmode.setFont(font)
        self.avaiablebooksbutton = QRadioButton(self.viewmode)
        self.avaiablebooksbutton.setObjectName(u"avaiablebooksbutton")
        self.avaiablebooksbutton.setGeometry(QRect(10, 30, 251, 28))
        self.avaiablebooksbutton.setFont(font)
        self.allbooksbutton = QRadioButton(self.viewmode)
        self.allbooksbutton.setObjectName(u"allbooksbutton")
        self.allbooksbutton.setGeometry(QRect(10, 60, 251, 28))
        self.allbooksbutton.setFont(font)
        self.sortby = QGroupBox(self.issuetab)
        self.sortby.setObjectName(u"sortby")
        self.sortby.setGeometry(QRect(670, 110, 271, 131))
        self.sortby.setFont(font)
        self.titlebutton = QRadioButton(self.sortby)
        self.titlebutton.setObjectName(u"titlebutton")
        self.titlebutton.setGeometry(QRect(10, 30, 251, 28))
        self.titlebutton.setFont(font)
        self.authorbutton = QRadioButton(self.sortby)
        self.authorbutton.setObjectName(u"authorbutton")
        self.authorbutton.setGeometry(QRect(10, 60, 251, 28))
        self.authorbutton.setFont(font)
        self.ratingbutton = QRadioButton(self.sortby)
        self.ratingbutton.setObjectName(u"ratingbutton")
        self.ratingbutton.setGeometry(QRect(10, 90, 251, 28))
        self.ratingbutton.setFont(font)
        self.layoutWidget = QWidget(self.issuetab)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(687, 348, 271, 183))
        self.layoutWidget.setFont(font)
        self.buttons = QVBoxLayout(self.layoutWidget)
        self.buttons.setObjectName(u"buttons")
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.refreshbutton = QPushButton(self.layoutWidget)
        self.refreshbutton.setObjectName(u"refreshbutton")
        self.refreshbutton.setMinimumSize(QSize(0, 40))
        font1 = QFont()
        font1.setFamilies([u"Trebuchet MS"])
        font1.setPointSize(13)
        font1.setBold(False)
        self.refreshbutton.setFont(font1)
        self.refreshbutton.setStyleSheet(u"background-color : purple;\n"
"color: white;")

        self.buttons.addWidget(self.refreshbutton)

        self.detailsbutton = QPushButton(self.layoutWidget)
        self.detailsbutton.setObjectName(u"detailsbutton")
        self.detailsbutton.setMinimumSize(QSize(0, 40))
        self.detailsbutton.setFont(font)
        self.detailsbutton.setStyleSheet(u"background-color : blue;\n"
"color: white;")

        self.buttons.addWidget(self.detailsbutton)

        self.issuebutton = QPushButton(self.layoutWidget)
        self.issuebutton.setObjectName(u"issuebutton")
        self.issuebutton.setMinimumSize(QSize(0, 40))
        self.issuebutton.setFont(font)
        self.issuebutton.setStyleSheet(u"background-color : green;\n"
"color: white;")

        self.buttons.addWidget(self.issuebutton)

        self.adminbutton = QPushButton(self.layoutWidget)
        self.adminbutton.setObjectName(u"adminbutton")
        self.adminbutton.setMinimumSize(QSize(0, 40))
        self.adminbutton.setFont(font)
        self.adminbutton.setStyleSheet(u"background-color : red;\n"
"color: white;")

        self.buttons.addWidget(self.adminbutton)

        self.booklist = QListWidget(self.issuetab)
        self.booklist.setObjectName(u"booklist")
        self.booklist.setGeometry(QRect(15, 11, 631, 491))
        self.booklist.setFont(font)
        self.errorlabel = QLabel(self.issuetab)
        self.errorlabel.setObjectName(u"errorlabel")
        self.errorlabel.setGeometry(QRect(14, 510, 631, 21))
        self.errorlabel.setFont(font1)
        self.errorlabel.setStyleSheet(u"color: red")
        self.tabWidget.addTab(self.issuetab, "")
        self.deposittab = QWidget()
        self.deposittab.setObjectName(u"deposittab")
        self.memberlabel = QLabel(self.deposittab)
        self.memberlabel.setObjectName(u"memberlabel")
        self.memberlabel.setGeometry(QRect(590, 10, 149, 41))
        self.idfield = QLineEdit(self.deposittab)
        self.idfield.setObjectName(u"idfield")
        self.idfield.setGeometry(QRect(750, 10, 211, 41))
        self.viewbookbutton = QPushButton(self.deposittab)
        self.viewbookbutton.setObjectName(u"viewbookbutton")
        self.viewbookbutton.setGeometry(QRect(590, 110, 371, 29))
        self.returnbooklist = QListWidget(self.deposittab)
        self.returnbooklist.setObjectName(u"returnbooklist")
        self.returnbooklist.setGeometry(QRect(10, 10, 551, 511))
        self.returnbooklist.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.errorlabel_2 = QLabel(self.deposittab)
        self.errorlabel_2.setObjectName(u"errorlabel_2")
        self.errorlabel_2.setGeometry(QRect(590, 70, 371, 22))
        self.errorlabel_2.setStyleSheet(u"color: red\n"
"")
        self.line_2 = QFrame(self.deposittab)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(560, 200, 421, 21))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.returnbutton = QPushButton(self.deposittab)
        self.returnbutton.setObjectName(u"returnbutton")
        self.returnbutton.setGeometry(QRect(690, 450, 171, 61))
        self.viewbookhistorybutton = QPushButton(self.deposittab)
        self.viewbookhistorybutton.setObjectName(u"viewbookhistorybutton")
        self.viewbookhistorybutton.setGeometry(QRect(590, 160, 371, 29))
        self.onestar = QRadioButton(self.deposittab)
        self.onestar.setObjectName(u"onestar")
        self.onestar.setGeometry(QRect(590, 270, 140, 28))
        self.twostar = QRadioButton(self.deposittab)
        self.twostar.setObjectName(u"twostar")
        self.twostar.setGeometry(QRect(590, 300, 140, 28))
        self.threestar = QRadioButton(self.deposittab)
        self.threestar.setObjectName(u"threestar")
        self.threestar.setGeometry(QRect(590, 330, 140, 28))
        self.fourstar = QRadioButton(self.deposittab)
        self.fourstar.setObjectName(u"fourstar")
        self.fourstar.setGeometry(QRect(590, 360, 140, 28))
        self.fivestar = QRadioButton(self.deposittab)
        self.fivestar.setObjectName(u"fivestar")
        self.fivestar.setGeometry(QRect(590, 390, 140, 28))
        self.ratinglabel = QLabel(self.deposittab)
        self.ratinglabel.setObjectName(u"ratinglabel")
        self.ratinglabel.setGeometry(QRect(590, 230, 371, 31))
        self.tabWidget.addTab(self.deposittab, "")

        self.formLayout.setWidget(0, QFormLayout.SpanningRole, self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Library Management System", None))
        self.genrelabel.setText(QCoreApplication.translate("MainWindow", u"Genre:", None))
        self.viewmode.setTitle(QCoreApplication.translate("MainWindow", u"View mode:", None))
        self.avaiablebooksbutton.setText(QCoreApplication.translate("MainWindow", u"Books available", None))
        self.allbooksbutton.setText(QCoreApplication.translate("MainWindow", u"All books", None))
        self.sortby.setTitle(QCoreApplication.translate("MainWindow", u"Sort by:", None))
        self.titlebutton.setText(QCoreApplication.translate("MainWindow", u"Title", None))
        self.authorbutton.setText(QCoreApplication.translate("MainWindow", u"Author", None))
        self.ratingbutton.setText(QCoreApplication.translate("MainWindow", u"Rating", None))
        self.refreshbutton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.detailsbutton.setText(QCoreApplication.translate("MainWindow", u"Details", None))
        self.issuebutton.setText(QCoreApplication.translate("MainWindow", u"Issue", None))
        self.adminbutton.setText(QCoreApplication.translate("MainWindow", u"Admin", None))
        self.errorlabel.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.issuetab), QCoreApplication.translate("MainWindow", u"Issue Book", None))
        self.memberlabel.setText(QCoreApplication.translate("MainWindow", u"Enter Member ID:", None))
        self.viewbookbutton.setText(QCoreApplication.translate("MainWindow", u"View books issued", None))
        self.errorlabel_2.setText("")
        self.returnbutton.setText(QCoreApplication.translate("MainWindow", u"Return Book", None))
        self.viewbookhistorybutton.setText(QCoreApplication.translate("MainWindow", u"View history of books issued", None))
        self.onestar.setText(QCoreApplication.translate("MainWindow", u"\u2b50", None))
        self.twostar.setText(QCoreApplication.translate("MainWindow", u"\u2b50\u2b50", None))
        self.threestar.setText(QCoreApplication.translate("MainWindow", u"\u2b50\u2b50\u2b50", None))
        self.fourstar.setText(QCoreApplication.translate("MainWindow", u"\u2b50\u2b50\u2b50\u2b50", None))
        self.fivestar.setText(QCoreApplication.translate("MainWindow", u"\u2b50\u2b50\u2b50\u2b50\u2b50", None))
        self.ratinglabel.setText(QCoreApplication.translate("MainWindow", u"Leave a rating for the book:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.deposittab), QCoreApplication.translate("MainWindow", u"Deposit Book", None))
    # retranslateUi

