# Form implementation generated from reading ui file 'UI/uifiles/addbooks.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addbookdialog(object):
    def setupUi(self, addbookdialog):
        addbookdialog.setObjectName("addbookdialog")
        addbookdialog.resize(450, 400)
        addbookdialog.setMinimumSize(QtCore.QSize(450, 400))
        addbookdialog.setMaximumSize(QtCore.QSize(450, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(addbookdialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(addbookdialog)
        self.tabWidget.setObjectName("tabWidget")
        self.manual = QtWidgets.QWidget()
        self.manual.setObjectName("manual")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.manual)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputform = QtWidgets.QFormLayout()
        self.inputform.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.inputform.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputform.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputform.setContentsMargins(10, -1, 10, -1)
        self.inputform.setHorizontalSpacing(40)
        self.inputform.setVerticalSpacing(25)
        self.inputform.setObjectName("inputform")
        self.titlefield = QtWidgets.QLabel(self.manual)
        font = QtGui.QFont()
        font.setBold(True)
        self.titlefield.setFont(font)
        self.titlefield.setObjectName("titlefield")
        self.inputform.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.titlefield)
        self.inputtitle = QtWidgets.QLineEdit(self.manual)
        self.inputtitle.setMinimumSize(QtCore.QSize(0, 30))
        self.inputtitle.setObjectName("inputtitle")
        self.inputform.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputtitle)
        self.authorfield = QtWidgets.QLabel(self.manual)
        font = QtGui.QFont()
        font.setBold(True)
        self.authorfield.setFont(font)
        self.authorfield.setObjectName("authorfield")
        self.inputform.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.authorfield)
        self.inputauthor = QtWidgets.QLineEdit(self.manual)
        self.inputauthor.setMinimumSize(QtCore.QSize(0, 30))
        self.inputauthor.setObjectName("inputauthor")
        self.inputform.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputauthor)
        self.genrefield = QtWidgets.QLabel(self.manual)
        font = QtGui.QFont()
        font.setBold(True)
        self.genrefield.setFont(font)
        self.genrefield.setObjectName("genrefield")
        self.inputform.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.genrefield)
        self.inputgenre = QtWidgets.QLineEdit(self.manual)
        self.inputgenre.setMinimumSize(QtCore.QSize(0, 30))
        self.inputgenre.setObjectName("inputgenre")
        self.inputform.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputgenre)
        self.totalfield = QtWidgets.QLabel(self.manual)
        font = QtGui.QFont()
        font.setBold(True)
        self.totalfield.setFont(font)
        self.totalfield.setObjectName("totalfield")
        self.inputform.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.totalfield)
        self.inputtotal = QtWidgets.QLineEdit(self.manual)
        self.inputtotal.setMinimumSize(QtCore.QSize(0, 30))
        self.inputtotal.setObjectName("inputtotal")
        self.inputform.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inputtotal)
        self.verticalLayout_2.addLayout(self.inputform)
        self.error = QtWidgets.QLabel(self.manual)
        font = QtGui.QFont()
        font.setBold(True)
        self.error.setFont(font)
        self.error.setStyleSheet("color: orange")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error.setObjectName("error")
        self.verticalLayout_2.addWidget(self.error)
        self.buttonlayout = QtWidgets.QHBoxLayout()
        self.buttonlayout.setObjectName("buttonlayout")
        self.clearbutton = QtWidgets.QPushButton(self.manual)
        self.clearbutton.setMinimumSize(QtCore.QSize(0, 25))
        self.clearbutton.setStyleSheet("QPushButton#clearbutton{\n"
"    background-color: cornflowerblue;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#clearbutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.clearbutton.setObjectName("clearbutton")
        self.buttonlayout.addWidget(self.clearbutton)
        self.submitbutton = QtWidgets.QPushButton(self.manual)
        self.submitbutton.setMinimumSize(QtCore.QSize(0, 25))
        self.submitbutton.setStyleSheet("QPushButton#submitbutton{\n"
"    background-color: green;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#submitbutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.submitbutton.setObjectName("submitbutton")
        self.buttonlayout.addWidget(self.submitbutton)
        self.closebutton = QtWidgets.QPushButton(self.manual)
        self.closebutton.setMinimumSize(QtCore.QSize(0, 25))
        self.closebutton.setStyleSheet("QPushButton#closebutton{\n"
"    background-color: #656565;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#closebutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.closebutton.setObjectName("closebutton")
        self.buttonlayout.addWidget(self.closebutton)
        self.verticalLayout_2.addLayout(self.buttonlayout)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 2)
        self.tabWidget.addTab(self.manual, "")
        self.isbn = QtWidgets.QWidget()
        self.isbn.setObjectName("isbn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.isbn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.isbnentry = QtWidgets.QHBoxLayout()
        self.isbnentry.setContentsMargins(10, -1, 10, -1)
        self.isbnentry.setSpacing(15)
        self.isbnentry.setObjectName("isbnentry")
        self.isbnlabel = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setBold(True)
        self.isbnlabel.setFont(font)
        self.isbnlabel.setObjectName("isbnlabel")
        self.isbnentry.addWidget(self.isbnlabel)
        self.isbnfield = QtWidgets.QLineEdit(self.isbn)
        self.isbnfield.setMinimumSize(QtCore.QSize(0, 30))
        self.isbnfield.setObjectName("isbnfield")
        self.isbnentry.addWidget(self.isbnfield)
        self.searchbuttonisbn = QtWidgets.QPushButton(self.isbn)
        self.searchbuttonisbn.setObjectName("searchbuttonisbn")
        self.isbnentry.addWidget(self.searchbuttonisbn)
        self.isbnentry.setStretch(0, 2)
        self.isbnentry.setStretch(1, 10)
        self.isbnentry.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.isbnentry)
        self.detailslayout = QtWidgets.QVBoxLayout()
        self.detailslayout.setContentsMargins(10, 5, 10, 5)
        self.detailslayout.setObjectName("detailslayout")
        self.headingisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.headingisbn.setFont(font)
        self.headingisbn.setStyleSheet("")
        self.headingisbn.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.headingisbn.setObjectName("headingisbn")
        self.detailslayout.addWidget(self.headingisbn)
        self.titleisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.titleisbn.setFont(font)
        self.titleisbn.setStyleSheet("")
        self.titleisbn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleisbn.setObjectName("titleisbn")
        self.detailslayout.addWidget(self.titleisbn)
        self.authorisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.authorisbn.setFont(font)
        self.authorisbn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.authorisbn.setObjectName("authorisbn")
        self.detailslayout.addWidget(self.authorisbn)
        self.publisherisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.publisherisbn.setFont(font)
        self.publisherisbn.setStyleSheet("")
        self.publisherisbn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.publisherisbn.setObjectName("publisherisbn")
        self.detailslayout.addWidget(self.publisherisbn)
        self.verticalLayout_4.addLayout(self.detailslayout)
        self.totallayout = QtWidgets.QHBoxLayout()
        self.totallayout.setContentsMargins(10, -1, 10, -1)
        self.totallayout.setSpacing(15)
        self.totallayout.setObjectName("totallayout")
        self.totallabelisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setBold(True)
        self.totallabelisbn.setFont(font)
        self.totallabelisbn.setObjectName("totallabelisbn")
        self.totallayout.addWidget(self.totallabelisbn)
        self.totalfieldisbn = QtWidgets.QLineEdit(self.isbn)
        self.totalfieldisbn.setMinimumSize(QtCore.QSize(0, 30))
        self.totalfieldisbn.setObjectName("totalfieldisbn")
        self.totallayout.addWidget(self.totalfieldisbn)
        self.verticalLayout_4.addLayout(self.totallayout)
        self.errorisbn = QtWidgets.QLabel(self.isbn)
        font = QtGui.QFont()
        font.setBold(True)
        self.errorisbn.setFont(font)
        self.errorisbn.setStyleSheet("color: orange")
        self.errorisbn.setText("")
        self.errorisbn.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorisbn.setObjectName("errorisbn")
        self.verticalLayout_4.addWidget(self.errorisbn)
        self.buttonlayoutisn = QtWidgets.QHBoxLayout()
        self.buttonlayoutisn.setObjectName("buttonlayoutisn")
        self.clearbuttonisbn = QtWidgets.QPushButton(self.isbn)
        self.clearbuttonisbn.setMinimumSize(QtCore.QSize(0, 25))
        self.clearbuttonisbn.setStyleSheet("QPushButton#clearbuttonisbn{\n"
"    background-color: cornflowerblue;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#clearbuttonisbn:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.clearbuttonisbn.setObjectName("clearbuttonisbn")
        self.buttonlayoutisn.addWidget(self.clearbuttonisbn)
        self.submitbuttonisbn = QtWidgets.QPushButton(self.isbn)
        self.submitbuttonisbn.setMinimumSize(QtCore.QSize(0, 25))
        self.submitbuttonisbn.setStyleSheet("QPushButton#submitbuttonisbn{\n"
"    background-color: green;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#submitbuttonisbn:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.submitbuttonisbn.setObjectName("submitbuttonisbn")
        self.buttonlayoutisn.addWidget(self.submitbuttonisbn)
        self.closebuttonisbn = QtWidgets.QPushButton(self.isbn)
        self.closebuttonisbn.setMinimumSize(QtCore.QSize(0, 25))
        self.closebuttonisbn.setStyleSheet("QPushButton#closebuttonisbn{\n"
"    background-color: #656565;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#closebuttonisbn:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.closebuttonisbn.setObjectName("closebuttonisbn")
        self.buttonlayoutisn.addWidget(self.closebuttonisbn)
        self.verticalLayout_4.addLayout(self.buttonlayoutisn)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 4)
        self.verticalLayout_4.setStretch(2, 2)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(4, 2)
        self.tabWidget.addTab(self.isbn, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(addbookdialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(addbookdialog)

    def retranslateUi(self, addbookdialog):
        _translate = QtCore.QCoreApplication.translate
        addbookdialog.setWindowTitle(_translate("addbookdialog", "Add Books"))
        self.titlefield.setText(_translate("addbookdialog", "Title:"))
        self.authorfield.setText(_translate("addbookdialog", "Author:"))
        self.genrefield.setText(_translate("addbookdialog", "Genre:"))
        self.totalfield.setText(_translate("addbookdialog", "Total:"))
        self.clearbutton.setText(_translate("addbookdialog", "Clear"))
        self.submitbutton.setText(_translate("addbookdialog", "Submit"))
        self.closebutton.setText(_translate("addbookdialog", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manual), _translate("addbookdialog", "Manual Entry"))
        self.isbnlabel.setText(_translate("addbookdialog", "ISBN:"))
        self.searchbuttonisbn.setText(_translate("addbookdialog", "Search"))
        self.headingisbn.setText(_translate("addbookdialog", "Book Details:"))
        self.titleisbn.setText(_translate("addbookdialog", "-"))
        self.authorisbn.setText(_translate("addbookdialog", "-"))
        self.publisherisbn.setText(_translate("addbookdialog", "-"))
        self.totallabelisbn.setText(_translate("addbookdialog", "Total:"))
        self.clearbuttonisbn.setText(_translate("addbookdialog", "Clear"))
        self.submitbuttonisbn.setText(_translate("addbookdialog", "Submit"))
        self.closebuttonisbn.setText(_translate("addbookdialog", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.isbn), _translate("addbookdialog", "Search using ISBN"))
