# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/uifiles/deletebooks.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deletebookdialog(object):
    def setupUi(self, deletebookdialog):
        deletebookdialog.setObjectName("deletebookdialog")
        deletebookdialog.resize(550, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(deletebookdialog.sizePolicy().hasHeightForWidth())
        deletebookdialog.setSizePolicy(sizePolicy)
        deletebookdialog.setMinimumSize(QtCore.QSize(550, 230))
        deletebookdialog.setMaximumSize(QtCore.QSize(550, 230))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        deletebookdialog.setFont(font)
        self.booklist = QtWidgets.QListWidget(deletebookdialog)
        self.booklist.setGeometry(QtCore.QRect(10, 10, 391, 181))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.booklist.setFont(font)
        self.booklist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.booklist.setObjectName("booklist")
        self.errorlabel = QtWidgets.QLabel(deletebookdialog)
        self.errorlabel.setGeometry(QtCore.QRect(10, 200, 481, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.errorlabel.setFont(font)
        self.errorlabel.setStyleSheet("color: red")
        self.errorlabel.setText("")
        self.errorlabel.setObjectName("errorlabel")
        self.layoutWidget = QtWidgets.QWidget(deletebookdialog)
        self.layoutWidget.setGeometry(QtCore.QRect(410, 10, 132, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttons = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.buttons.setSpacing(10)
        self.buttons.setObjectName("buttons")
        self.deletebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.deletebutton.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deletebutton.setFont(font)
        self.deletebutton.setStyleSheet("background-color : red;\n"
"color: white;")
        self.deletebutton.setObjectName("deletebutton")
        self.buttons.addWidget(self.deletebutton)
        self.closebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.closebutton.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.closebutton.setFont(font)
        self.closebutton.setStyleSheet("")
        self.closebutton.setObjectName("closebutton")
        self.buttons.addWidget(self.closebutton)

        self.retranslateUi(deletebookdialog)
        QtCore.QMetaObject.connectSlotsByName(deletebookdialog)

    def retranslateUi(self, deletebookdialog):
        _translate = QtCore.QCoreApplication.translate
        deletebookdialog.setWindowTitle(_translate("deletebookdialog", "Delete Books"))
        self.deletebutton.setText(_translate("deletebookdialog", "Delete"))
        self.closebutton.setText(_translate("deletebookdialog", "Close"))
