# Form implementation generated from reading ui file 'UI/uifiles/issuebook.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_issuebookdialog(object):
    def setupUi(self, issuebookdialog):
        issuebookdialog.setObjectName("issuebookdialog")
        issuebookdialog.resize(500, 230)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(issuebookdialog.sizePolicy().hasHeightForWidth())
        issuebookdialog.setSizePolicy(sizePolicy)
        issuebookdialog.setMinimumSize(QtCore.QSize(500, 230))
        issuebookdialog.setMaximumSize(QtCore.QSize(500, 230))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        issuebookdialog.setFont(font)
        self.memlist = QtWidgets.QListWidget(issuebookdialog)
        self.memlist.setGeometry(QtCore.QRect(10, 10, 341, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        self.memlist.setFont(font)
        self.memlist.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.memlist.setObjectName("memlist")
        self.issuelabel = QtWidgets.QLabel(issuebookdialog)
        self.issuelabel.setGeometry(QtCore.QRect(10, 200, 481, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.issuelabel.setFont(font)
        self.issuelabel.setStyleSheet("color: blue")
        self.issuelabel.setText("")
        self.issuelabel.setObjectName("issuelabel")
        self.layoutWidget = QtWidgets.QWidget(issuebookdialog)
        self.layoutWidget.setGeometry(QtCore.QRect(360, 10, 132, 181))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.buttons = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.buttons.setContentsMargins(0, 0, 0, 0)
        self.buttons.setSpacing(10)
        self.buttons.setObjectName("buttons")
        self.issuebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.issuebutton.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.issuebutton.setFont(font)
        self.issuebutton.setStyleSheet("background-color : blue;\n"
"color: white;")
        self.issuebutton.setObjectName("issuebutton")
        self.buttons.addWidget(self.issuebutton)
        self.closebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.closebutton.setMinimumSize(QtCore.QSize(130, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.closebutton.setFont(font)
        self.closebutton.setStyleSheet("background-color: #333333;\n"
"color: white;")
        self.closebutton.setObjectName("closebutton")
        self.buttons.addWidget(self.closebutton)

        self.retranslateUi(issuebookdialog)
        QtCore.QMetaObject.connectSlotsByName(issuebookdialog)

    def retranslateUi(self, issuebookdialog):
        _translate = QtCore.QCoreApplication.translate
        issuebookdialog.setWindowTitle(_translate("issuebookdialog", "Issue Book"))
        self.issuebutton.setText(_translate("issuebookdialog", "Issue"))
        self.closebutton.setText(_translate("issuebookdialog", "Close"))
