# Form implementation generated from reading ui file 'UI/uifiles/pwd.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_passworddialog(object):
    def setupUi(self, passworddialog):
        passworddialog.setObjectName("passworddialog")
        passworddialog.resize(400, 250)
        passworddialog.setMinimumSize(QtCore.QSize(400, 250))
        passworddialog.setMaximumSize(QtCore.QSize(400, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(passworddialog)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info = QtWidgets.QLabel(passworddialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.info.setFont(font)
        self.info.setObjectName("info")
        self.verticalLayout.addWidget(self.info)
        self.inputform = QtWidgets.QFormLayout()
        self.inputform.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.inputform.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputform.setFormAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputform.setContentsMargins(10, -1, 10, -1)
        self.inputform.setHorizontalSpacing(40)
        self.inputform.setVerticalSpacing(25)
        self.inputform.setObjectName("inputform")
        self.username = QtWidgets.QLabel(passworddialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.username.setFont(font)
        self.username.setObjectName("username")
        self.inputform.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.username)
        self.password = QtWidgets.QLabel(passworddialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.inputform.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.password)
        self.userfield = QtWidgets.QLineEdit(passworddialog)
        self.userfield.setMinimumSize(QtCore.QSize(0, 30))
        self.userfield.setObjectName("userfield")
        self.inputform.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.userfield)
        self.pwdfield = QtWidgets.QLineEdit(passworddialog)
        self.pwdfield.setMinimumSize(QtCore.QSize(0, 30))
        self.pwdfield.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pwdfield.setObjectName("pwdfield")
        self.inputform.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pwdfield)
        self.verticalLayout.addLayout(self.inputform)
        self.error = QtWidgets.QLabel(passworddialog)
        font = QtGui.QFont()
        font.setBold(True)
        self.error.setFont(font)
        self.error.setStyleSheet("color: orange")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        self.buttonlayout = QtWidgets.QHBoxLayout()
        self.buttonlayout.setObjectName("buttonlayout")
        self.clearbutton = QtWidgets.QPushButton(passworddialog)
        self.clearbutton.setMinimumSize(QtCore.QSize(0, 25))
        self.clearbutton.setStyleSheet("QPushButton#clearbutton{\n"
"    background-color: cornflowerblue;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#clearbutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.clearbutton.setObjectName("clearbutton")
        self.buttonlayout.addWidget(self.clearbutton)
        self.submitbutton = QtWidgets.QPushButton(passworddialog)
        self.submitbutton.setMinimumSize(QtCore.QSize(0, 25))
        self.submitbutton.setStyleSheet("QPushButton#submitbutton{\n"
"    background-color: green;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#submitbutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.submitbutton.setObjectName("submitbutton")
        self.buttonlayout.addWidget(self.submitbutton)
        self.closebutton = QtWidgets.QPushButton(passworddialog)
        self.closebutton.setMinimumSize(QtCore.QSize(0, 25))
        self.closebutton.setStyleSheet("QPushButton#closebutton{\n"
"    background-color: #656565;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton#closebutton:hover{\n"
"    border: 2px solid teal;\n"
"}")
        self.closebutton.setObjectName("closebutton")
        self.buttonlayout.addWidget(self.closebutton)
        self.verticalLayout.addLayout(self.buttonlayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 2)

        self.retranslateUi(passworddialog)
        QtCore.QMetaObject.connectSlotsByName(passworddialog)

    def retranslateUi(self, passworddialog):
        _translate = QtCore.QCoreApplication.translate
        passworddialog.setWindowTitle(_translate("passworddialog", "Admin Login"))
        self.info.setText(_translate("passworddialog", "Login to access admin portal"))
        self.username.setText(_translate("passworddialog", "Username:"))
        self.password.setText(_translate("passworddialog", "Password:"))
        self.clearbutton.setText(_translate("passworddialog", "Clear"))
        self.submitbutton.setText(_translate("passworddialog", "Submit"))
        self.closebutton.setText(_translate("passworddialog", "Close"))
